export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
export const CREATE_TRANSACTION_USE_CASE = 'CREATE_TRANSACTION_USE_CASE';
export const UPDATE_TRANSACTION_STATUS_USE_CASE =
  'UPDATE_TRANSACTION_STATUS_USE_CASE';
export const TRANSACTION_PRODUCER = 'TRANSACTION_PRODUCER';

export const PROVIDERS = {
  TRANSACTION_REPOSITORY,
  CREATE_TRANSACTION_USE_CASE,
  TRANSACTION_PRODUCER,
  UPDATE_TRANSACTION_STATUS_USE_CASE,
};
